### PR TITLE
Add default client variable

### PR DESCRIPTION
**Pull request by ShubhamRasal**
- initialize in init function
- add helpers method to use by default client

### CODE REVIEW

**Comment by ShubhamRasal** [comment]
default.go feel so generic. do you have any other name for file or location where I can move this functions?
cc @Mzack9999

**Comment by Mzack9999** [comment]
@ShubhamRasal if I had to suggest something, probably I'd go with `default_client.go` or `client.go`. In the standard library the `DefaultClient` is under `net/http/client.go`

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
Could you add a test that ensure the DefaultClient is not nil and we can perform at least one operation (e.g. GET)

**Review by Mzack9999 — APPROVED** [review]
lgtm!

**Pull request merged**
