### PR TITLE
Restore original request body in FromRequest function + Bump to go1.18

### LINKED ISSUE #32: FromRequest method should restore request body
### retryablehttp version:
`main`

### Current Behavior:
The function `FromRequest` consumes the body without restoring it

### Expected Behavior:
The original request body should be reusable

### Steps To Reproduce:
Ref: https://github.com/projectdiscovery/nuclei/pull/2924

### PR DESCRIPTION
**Pull request by Mzack9999**
Closes #32

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
- [ ] General syntax update consequent to bump to 1.18
- [ ] Check if the reader function can be simplified with ReusableReader

**Comment by tarunKoyalwar** [comment]
closes #30 

### Possible Explaination 

Each unit test created a new web server (buggy http) on same port . but each of them ran on goroutines . 
Instead of failing to bind to port . it could have caused race condition (at lower level). . Making all unit test use same server for testing fixed the issue

**Comment by tarunKoyalwar** [comment]
# Changes

- Simplified logic (related to request body reuse)
- Improvements and efficiency
- Added more unit test to avoid similar situations in future

**Comment by tarunKoyalwar** [comment]
Verified with https://github.com/projectdiscovery/nuclei/pull/2924 . Works as expected !!

**Comment by Mzack9999** [comment]
Excellent work - It seems much more uniform and efficient now, additionally the underlying http.Transport won't be locked into I/O waiting operations. Not related to this PR, but I'd also like to add these changes related to the `lint-test.yml` action:
- [ ] Add checkout v3
- [ ] Add `actions/setup-go@v3` before calling `golangci-lint-action` (a few times, the analyzer got stuck due to missing go environment)

**Comment by Mzack9999** [comment]
lgtm - merging

**Pull request merged**
